Performing system checks...

System check identified no issues (0 silenced).
August 12, 2017 - 13:54:53
Django version 1.11.4, using settings 'learning_log.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fec5e82c6a8>
Traceback (most recent call last):
  File "/home/andreferreira/Documents/livro_python/learning_log/ll_env/lib/python3.5/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/andreferreira/Documents/livro_python/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/home/andreferreira/Documents/livro_python/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/andreferreira/Documents/livro_python/learning_log/ll_env/lib/python3.5/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/andreferreira/Documents/livro_python/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/andreferreira/Documents/livro_python/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/andreferreira/Documents/livro_python/learning_log/ll_env/lib/python3.5/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/andreferreira/Documents/livro_python/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/home/andreferreira/Documents/livro_python/learning_log/ll_env/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/andreferreira/Documents/livro_python/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/andreferreira/Documents/livro_python/learning_log/ll_env/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/andreferreira/Documents/livro_python/learning_log/ll_env/lib/python3.5/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/andreferreira/Documents/livro_python/learning_log/learning_log/urls.py", line 21, in <module>
    url(r'', include('learning_logs.urls', namespace='learning_logs'))
  File "/home/andreferreira/Documents/livro_python/learning_log/ll_env/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/andreferreira/Documents/livro_python/learning_log/learning_logs/urls.py", line 22, in <module>
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
AttributeError: module 'learning_logs.views' has no attribute 'edit_entry'
Performing system checks...

[12/Aug/2017 14:44:44] "GET / HTTP/1.1" 200 173
Not Found: /favicon.ico
[12/Aug/2017 14:44:44] "GET /favicon.ico HTTP/1.1" 404 3084
[12/Aug/2017 14:44:46] "GET /topics/ HTTP/1.1" 200 439
[12/Aug/2017 14:44:54] "GET /topics/4/ HTTP/1.1" 200 558
[12/Aug/2017 14:44:58] "GET /edit_entry/1/ HTTP/1.1" 200 691
[12/Aug/2017 14:45:11] "POST /edit_entry/1/ HTTP/1.1" 302 0
[12/Aug/2017 14:45:11] "GET /topics/4/ HTTP/1.1" 200 565
[12/Aug/2017 14:45:19] "GET / HTTP/1.1" 200 173
[12/Aug/2017 14:45:20] "GET /topics/ HTTP/1.1" 200 439
[12/Aug/2017 14:45:24] "GET /topics/2/ HTTP/1.1" 200 585
[12/Aug/2017 14:45:28] "GET /topics/ HTTP/1.1" 200 439
[12/Aug/2017 14:45:29] "GET /topics/3/ HTTP/1.1" 200 1451
[12/Aug/2017 14:47:12] "GET /topics/ HTTP/1.1" 200 439
[12/Aug/2017 14:47:13] "GET / HTTP/1.1" 200 173
[12/Aug/2017 14:47:14] "GET /topics/ HTTP/1.1" 200 439
[12/Aug/2017 14:47:20] "GET / HTTP/1.1" 200 173
[12/Aug/2017 14:47:22] "GET /topics/ HTTP/1.1" 200 439
Not Found: /favicon.ico
[12/Aug/2017 15:00:53] "GET /favicon.ico HTTP/1.1" 404 3084
[12/Aug/2017 21:19:05] "GET / HTTP/1.1" 200 173
Not Found: /favicon.ico
[12/Aug/2017 21:19:06] "GET /favicon.ico HTTP/1.1" 404 3084
[12/Aug/2017 21:19:08] "GET /topics/ HTTP/1.1" 200 439
[12/Aug/2017 21:19:10] "GET /topics/6/ HTTP/1.1" 200 373
[12/Aug/2017 21:19:16] "GET /edit_entry/5/ HTTP/1.1" 200 510
[12/Aug/2017 21:19:19] "GET /topics/ HTTP/1.1" 200 439
